---
HOSTS:
  el7-build-server:
    roles:
      - primary
    platform: el-7-x86_64
    hypervisor: docker
    # This needs to be the *oldest* image of EL7 to preserve SELinux build compatibility
    image: centos:7.0.1406
    docker_cmd: '/usr/sbin/sshd -D'
    docker_preserve_image: true
    docker_image_commands:
      # For SELinux Builds
      - 'yum install -y yum-utils'

      # We only want to deal with the original distro packages
      - 'yum-config-manager --disable \*'
      - 'echo -e "[legacy]\nname=Legacy\nbaseurl=http://vault.centos.org/7.0.1406/os/x86_64\ngpgkey=https://www.centos.org/keys/RPM-GPG-KEY-CentOS-7\ngpgcheck=1" > /etc/yum.repos.d/legacy.repo'

      # Downgrade ALL THE THINGS!!!
      - 'yum downgrade -y *'

      # Getting rid of package conflicts
      - 'yum remove -y fakesystemd'
      - '\cp -a /etc/ssh /root'
      - 'yum install -y openssh-server'
      - '\cp -a /root/ssh /etc'

      # Add the SELinux Build dependencies
      - 'yum install -y selinux-policy-targeted selinux-policy-devel policycoreutils policycoreutils-python'

      # Allow the build user to perform privileged operations
      - "echo 'Defaults:build_user !requiretty' >> /etc/sudoers"
      - "echo 'build_user ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers"

      # Add the build user
      - 'useradd -b /home -G wheel -m -c "Build User" -s /bin/bash -U build_user'

      # No limits
      - 'rm -rf /etc/security/limits.d/*.conf'

      # simp build-deps
      - 'yum-config-manager --enable extras'
      - 'yum install -y epel-release'
      - 'yum install -y openssl util-linux rpm-build augeas-devel createrepo genisoimage git gnupg2 libicu-devel libxml2 libxml2-devel libxslt libxslt-devel rpmdevtools clamav clamav-update which ruby-devel rpm-devel rpm-sign'

      # simp doc deps
      - 'yum -y install centos-release-scl python27 python-pip python-virtualenv fontconfig dejavu-sans-fonts dejavu-sans-mono-fonts dejavu-serif-fonts dejavu-fonts-common libjpeg-devel zlib-devel'

      # RVM build-deps
      - 'yum install -y libyaml-devel glibc-headers autoconf gcc gcc-c++ glibc-devel readline-devel libffi-devel openssl-devel automake libtool bison sqlite-devel'

      # For things that want to call systemctl - we don't need them for this
      - 'ln -sf /bin/true /usr/bin/systemctl'

      # Puppet Deps
      - 'yum install -y ntpdate rubygems'

      # RVM
      - 'runuser build_user -l -c "gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3"'
      - 'runuser build_user -l -c "curl -sSL https://get.rvm.io | bash -s stable"'
      - 'runuser build_user -l -c "rvm install 2.1.9"'
      - 'runuser build_user -l -c "rvm use --default 2.1.9"'
      - 'runuser build_user -l -c "rvm all do gem install bundler"'

      # Add some gems that will drag along 90% of what the build requires
      - 'runuser build_user -l -c "rvm use default; gem install --no-ri --no-rdoc simp-rake-helpers"'
      - 'runuser build_user -l -c "rvm use default; gem install --no-ri --no-rdoc json"'
      - 'runuser build_user -l -c "rvm use default; gem install --no-ri --no-rdoc charlock_holmes"'
      - 'runuser build_user -l -c "rvm use default; gem install --no-ri --no-rdoc posix-spawn"'

  el6-build-server:
    roles:
      - disabled
      - secondary
    platform: el-6-x86_64
    hypervisor: docker
    # This needs to be the *oldest* image of EL6 to preserve SELinux build compatibility
    image: centos:6.6
    docker_preserve_image: true
    docker_image_commands:
      # For SELinux Builds
      - 'yum install -y yum-utils'

      # We only want to deal with the original distro packages
      - 'yum-config-manager --disable \*'
      - 'echo -e "[legacy]\nname=Legacy\nbaseurl=http://vault.centos.org/6.6/os/x86_64\ngpgkey=https://www.centos.org/keys/RPM-GPG-KEY-CentOS-6\ngpgcheck=1" > /etc/yum.repos.d/legacy.repo'

      # Downgrade ALL THE THINGS!!!
      - 'yum downgrade -y *'

      # Getting rid of package conflicts
      - '\cp -a /etc/ssh /root'
      - 'yum install -y openssh-server'
      - '\cp -a /root/ssh /etc'

      # Add the SELinux Build dependencies
      - 'yum install -y selinux-policy-targeted selinux-policy-devel policycoreutils policycoreutils-python'

      # Allow the build user to perform privileged operations
      - "echo 'Defaults:build_user !requiretty' >> /etc/sudoers"
      - "echo 'build_user ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers"

      # Add the build user
      - 'useradd -b /home -G wheel -m -c "Build User" -s /bin/bash -U build_user'

      # No limits
      - 'rm -rf /etc/security/limits.d/*.conf'

      # simp build-deps
      - 'yum-config-manager --enable extras'
      - 'yum install -y epel-release'
      - 'yum install -y openssl util-linux rpm-build augeas-devel createrepo genisoimage git gnupg2 libicu-devel libxml2 libxml2-devel libxslt libxslt-devel rpmdevtools clamav which ruby-devel rpm-sign acl'

      # simp doc deps
      - 'yum -y install centos-release-scl python27 python-pip python-virtualenv fontconfig dejavu-sans-fonts dejavu-sans-mono-fonts dejavu-serif-fonts dejavu-fonts-common libjpeg-devel zlib-devel'

      # RVM build-deps
      - 'yum install -y libyaml-devel glibc-headers autoconf gcc gcc-c++ glibc-devel readline-devel libffi-devel openssl-devel automake libtool bison sqlite-devel tar'

      # Puppet Deps
      - 'yum install -y ntpdate rubygems'

      # RVM
      - 'runuser build_user -l -c "gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3"'
      - 'runuser build_user -l -c "curl -sSL https://get.rvm.io | bash -s stable"'
      - 'runuser build_user -l -c "rvm install 2.1.9"'
      - 'runuser build_user -l -c "rvm use --default 2.1.9"'
      - 'runuser build_user -l -c "rvm all do gem install bundler"'

      # Add some gems that will drag along 90% of what the build requires
      - 'runuser build_user -l -c "rvm use default; gem install --no-ri --no-rdoc simp-rake-helpers"'
      - 'runuser build_user -l -c "rvm use default; gem install --no-ri --no-rdoc json"'
      - 'runuser build_user -l -c "rvm use default; gem install --no-ri --no-rdoc charlock_holmes"'
      - 'runuser build_user -l -c "rvm use default; gem install --no-ri --no-rdoc posix-spawn"'

CONFIG:
  mount_folders:
    simp_core:
      host_path: './'
      container_path: '/simp-core'
  log_level: verbose
  type: aio
